@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.enginecrafter77.livelyrealms.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;