@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.enginecrafter77.livelyrealms.entity.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;