@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.enginecrafter77.livelyrealms.items;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;