@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.enginecrafter77.livelyrealms;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
